name: tests
# Note: name shows up in a badge. Be careful about renaming.

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      # Java 17 needed for resolving the Android Gradle Plugin
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache Kotlin Native compiler
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: kotlin-native-compiler-${{ runner.OS }}

      - name: Override Kotlin Version for testing
        run: echo "KOTLIN_VERSION_OVERRIDE=2.0.0" >> $GITHUB_ENV

      - name: Test with Gradle
        run: ./gradlew allTests --no-daemon
